Repository Kmc2000/sephora, pull requests merged in 2021-05, with the labels that each got.

#33 Adds Marine Frigate
  _maps/templates/boarding/syndicate/marine_frigate.dmm
  code/controllers/subsystem/job.dm
  nsv13/code/modules/overmap/boarding/ghost_role_spawners.dm
  nsv13/code/modules/overmap/types/syndicate.dm
Labels: mapping

#34 Pilot split
  _maps/map_files/Aetherwhisp/Aetherwhisp2.dmm
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Atlas/job_changes.dm
  _maps/map_files/Eclipse/job_changes.dm
  _maps/map_files/Gladius/Gladius1.dmm
  _maps/map_files/Instanced/map_files/Babylon1.dmm
  _maps/map_files/Jeppison/job_changes.dm
  _maps/map_files/Pegasus/job_changes.dm
  _maps/map_files/Tycoon/Tycoon1.dmm
  _maps/map_files/Tycoon/Tycoon2.dmm
  _maps/map_files/Tycoon/job_changes.dm
  _maps/map_files/jollysausage/job_changes.dm
  code/__DEFINES/access.dm
  code/__DEFINES/jobs.dm
  code/__DEFINES/preferences.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/antagonists/blob/structures/_blob.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/access.dm
  code/modules/jobs/jobs.dm
  icons/mob/hud.dmi
  icons/mob/landmarks.dmi
  nsv13.dme
  nsv13/code/game/general_quarters/dropship_types.dm
  nsv13/code/game/general_quarters/squad.dm
  nsv13/code/game/general_quarters/squad2.dm
  nsv13/code/game/machinery/munitions_machinery.dm
  nsv13/code/game/objects/structures/custom_closets.dm
  nsv13/code/modules/clothing/custom_clothes.dm
  nsv13/code/modules/jobs/faction.dm
  nsv13/code/modules/jobs/job_types/air_traffic_controller.dm
  nsv13/code/modules/jobs/job_types/fighter_pilot.dm
  nsv13/code/modules/jobs/job_types/fighter_technician.dm
  nsv13/code/modules/jobs/job_types/master_at_arms.dm
  nsv13/code/modules/jobs/job_types/munitions_technician.dm
  nsv13/code/modules/jobs/job_types/pilot.dm
  nsv13/code/modules/overmap/fighters/fighters2.dm
  nsv13/icons/mob/head.dmi
  nsv13/icons/mob/uniform.dmi
  nsv13/icons/obj/clothing/hats.dmi
  nsv13/icons/obj/clothing/uniforms.dmi
  nsv13/icons/obj/custom_closets.dmi
Labels: mapping, sprites

#35 Map things
  _maps/map_files/Aetherwhisp/Aetherwhisp2.dmm
  _maps/map_files/Atlas/atlas.dmm
  _maps/map_files/Gladius/Gladius1.dmm
  _maps/map_files/Instanced/map_files/SpaceSHIP.dmm
  _maps/map_files/Mining/nsv13/Rook.dmm
  _maps/map_files/Tycoon/Tycoon1.dmm
Labels: mapping

#37 Z
  code/datums/traits/negative.dm
  code/game/gamemodes/traitor/traitor.dm
  code/modules/jobs/access.dm
  config/jobs.txt
  config/ranks/sharpe.txt
Labels: Config Update

#38 Galactica things
  _maps/map_files/Galactica/space_SHIP.dmm
  nsv13/code/game/areas.dm
  nsv13/code/game/turfs/custom_turfs.dm
  nsv13/code/modules/overmap/pdsr.dm
Labels: mapping

#40 Unfucks more maps
  _maps/arenas/clockwork.dmm
  _maps/map_files/Aetherwhisp/Aetherwhisp2.dmm
  _maps/map_files/Gladius/Gladius1.dmm
Labels: mapping

#41 Guess you're getting another PR
  _maps/templates/boarding/dropship_main.dmm
  _maps/templates/boarding/gunship.dmm
  _maps/templates/boarding/syndicate/destroyer.dmm
  _maps/templates/boarding/syndicate/mako.dmm
  _maps/templates/boarding/syndicate/mako_carrier.dmm
  _maps/templates/pirate_pod.dmm
Labels: mapping

#44 Multi-z pipe fix
  _maps/map_files/Galactica/space_SHIP.dmm
  _maps/shuttles/ferry_galactica.dmm
  code/modules/atmospherics/multiz.dm
  icons/obj/atmos.dmi
  nsv13/code/game/objects/structures/custom_closets.dm
Labels: mapping, sprites

#45 Update again
  _maps/map_files/Galactica/space_SHIP.dmm
Labels: mapping

#46 More Galactica
  _maps/map_files/Galactica/space_SHIP.dmm
Labels: mapping
